baseURL: https://tanzsportclub.vfl-sindelfingen.de/
languageCode: de
title: TSC im VfL Sindelfingen e.V.
theme: tsc_vfl
relativeUrls: true

sitemap:
  changeFreq: daily

build:
  writeStats: true

enableInlineShortcodes: true
# sectionPagesMenu: "main"
# refLinksErrorLevel: WARNING
timeout: "90s"
