baseURL: http://example.org/
languageCode: de
title: TSC im VfL Sindelfingen e.V.
theme: tsc_vfl
relativeUrls: true

build:
  writeStats: true

enableInlineShortcodes: true
# sectionPagesMenu: "main"
# refLinksErrorLevel: WARNING
timeout: "90s"
